In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv('vgsales.csv')

## **Comprendiendo el negocio**

**Objetivo del negocio**

Una empresa dedicada a la distribución y comercialización de videojuegos desea comprender cuáles son los factores que influyen en el éxito comercial de un videojuego. La organización busca identificar tendencias relacionadas con plataformas, géneros, años de lanzamiento y regiones geográficas para apoyar la toma de decisiones sobre futuras inversiones, campañas de marketing y selección de títulos para su catálogo.

**Objetivos analíticos**

Se busca obtener datos relevantes dentro de la industria, principalmente para responder las siguientes incognitas:

lgunas preguntas que responderá el proyecto:

- ¿Qué plataformas han generado mayores ventas?
- ¿Qué géneros son los más exitosos?
- ¿Cómo evolucionan las ventas a través de los años?
- ¿Qué editoras publican los videojuegos con mayores ventas?
- ¿Existen diferencias entre Norteamérica, Europa y Japón?
- ¿Qué características poseen los videojuegos más vendidos?

# **Comprendiendo los datos**

In [15]:
list(df.columns)

['Rank',
 'Name',
 'Platform',
 'Year',
 'Genre',
 'Publisher',
 'NA_Sales',
 'EU_Sales',
 'JP_Sales',
 'Other_Sales',
 'Global_Sales']

Las columnas dentro del dataset y sus significado son las siguientes:

- **Rank**: Clasificación de ventas totales.
- **Name**: El nombre del juego.
- **Platform**: Plataforma de lanzamiento de los juegos.
- **Year**: Año en que se lanzo el juego.
- **Genere**: Genero del juego.
- **Publisher**: Editor del juego.
- **NA_Sales**: Ventas en norte america (en millones).
- **EU_Sales**: Ventas en europa (en millones).
- **JP_Sales**: Ventas en japon.
- **Other_sales**: Ventas en el resto del mundo.
- **Global Sales**: Total de ventas mundiales.

In [6]:
print("--------------Primeras 5 filas del dataset------------------")
df.head()

--------------Primeras 5 filas del dataset------------------

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [7]:
print("\n--- Dimensiones (Filas, Columnas) ---")
print(f"Filas: {df.shape[0]}")
print(f"Columnas: {df.shape[1]}")

--- Dimensiones (Filas, Columnas) ---
Filas: 16598
Columnas: 11

In [9]:
print("\n--- Información General ---")
df.describe()

--- Información General ---

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8300.605254,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.853933,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4151.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8300.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12449.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16600.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [19]:
print("\n--- Tipos de datos de cada variable ---")
variables_numericas = df.select_dtypes(include="number").columns

variables_categoricas = df.select_dtypes(include="object").columns

print("Variables numéricas")
print(variables_numericas)

print()

print("Variables categóricas")
print(variables_categoricas)

--- Tipos de datos de cada variable ---
Variables numéricas
Index(['Rank', 'Year', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales',
       'Global_Sales'],
      dtype='object')

Variables categóricas
Index(['Name', 'Platform', 'Genre', 'Publisher'], dtype='object')

In [23]:
print("\n--- Busqueda de valores nulos ---")
df.isnull().sum()

--- Busqueda de valores nulos ---

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [24]:
print("\n--- Porcentaje de valores nulos ---")
(df.isnull().sum() / len(df)) * 100

--- Porcentaje de valores nulos ---

Rank            0.000000
Name            0.000000
Platform        0.000000
Year            1.632727
Genre           0.000000
Publisher       0.349440
NA_Sales        0.000000
EU_Sales        0.000000
JP_Sales        0.000000
Other_Sales     0.000000
Global_Sales    0.000000
dtype: float64

In [28]:
print("\n--- Busqueda de filas duplicadas ---")
df.duplicated().sum()

--- Busqueda de filas duplicadas ---

np.int64(0)

In [30]:
print("\n--- Busqueda de valores unicos ---")
df.nunique()

--- Busqueda de valores unicos ---

Rank            16598
Name            11493
Platform           31
Year               39
Genre              12
Publisher         578
NA_Sales          409
EU_Sales          305
JP_Sales          244
Other_Sales       157
Global_Sales      623
dtype: int64